app:
  name: "Dinrx"
  domain: "dinrx.com"
  subdomain: "trade"
ssl:
  enabled: true    # Make sure to enable during deployment
  email: "support@dinrx.com"
license:
  url: "https://www.openware.com/api/v2/tenko"
  key: "PASTE-KEY-HERE"
images:
  peatio: rubykube/peatio:2.3.43
  barong: rubykube/barong:2.3.36
  frontend: gitlab.tunex.io:5050/arg/baseapp
  tower: quay.io/openware/tower:2.3.138
  postmaster: quay.io/openware/postmaster:2.3.4
rabbitmq:
  username: "guest"
  password: "changeme"
vendor:
  frontend: git@github.com:openware/baseapp.git
storage:
  provider: "Google"
  bucketName: "opendax-barong-docs-bucket"
  accessKey: "**********"
  secretKey: "**********"
twilio:
  phone_number: "+13236213650"
  account_sid: "ACb7da3ff9d7af882a97d8b776118b4758"
  auth_token: "68adb4338b69d1bcefde7a3f3a521c51"
recaptcha:
  type: "none"
  siteKey: "changeme"
  secretKey: "changeme"
smtp:
  host: smtp.hostinger.in
  port: 587
  user: support@dinrx.com
  password: Little27.
  sender_email: noreply@dinrx.com
  sender_name: Support
wallets:
  - kind: deposit
    address: "changeme"
    max_balance: 0.0
    secret: changeme
  - kind: hot
    address: "changeme"
    max_balance: 100.0
    secret: changeme
  - kind: warm
    address: "changeme"
    max_balance: 1000.0
    secret: changeme
terraform:
  credentials: "~/safe/opendax.json"
  project: "example-opendax"
  region: "europe-west4"
  zone: "europe-west4-a"
  instance_name: "opendax-cloud"
  machine_type: "n1-standard-4"
  image: "debian-cloud/debian-9"

